version: '3.7'
services:
  zeus:
    image: zeus:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L
    environment:
      NODE_ENV: development
    volumes:
      - ./zeus/src:/home/node/app/src
      